# Generated by Django 5.1.3 on 2024-11-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리 목록'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_at'], 'verbose_name': '게시글', 'verbose_name_plural': '게시글 목록'},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-create_at'], name='mgw_post_create__b0e7a5_idx'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='mgw_category',
        ),
        migrations.AlterModelTable(
            name='post',
            table='mgw_post',
        ),
    ]
