# Generated by Django 5.1.3 on 2024-12-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='desription',
            new_name='description',
        ),
    ]
